#!/bin/bash
# Write vault/system/host.md: where this project runs and how its apps are served. No model tokens.
# Run at setup and daily by the `host-facts` job; the Manager reads the page at session start, and every
# bot uses it before assuming an OS, a GPU, a path style or how to start something.
set -uo pipefail
export PATH="$HOME/.local/bin:$PATH"
OUT="$HOME/vault/system/host.md"
NAME="$(basename "$HOME")"
REG=/srv/projects/registry.yaml
API="$(awk -v k="  $NAME:" '$0==k{f=1;next} f&&/^  [^ ]/{f=0} f&&/api_port:/{print $2;exit}' "$REG" 2>/dev/null)"
OS="$(. /etc/os-release 2>/dev/null && echo "$PRETTY_NAME")"
CPU="$(awk -F': ' '/model name/{print $2; exit}' /proc/cpuinfo) ($(nproc) threads)"
RAM="$(awk '/MemTotal/{printf "%.0f GB", $2/1048576}' /proc/meminfo)"
GPU="$(command -v nvidia-smi >/dev/null && nvidia-smi --query-gpu=name,memory.total --format=csv,noheader 2>/dev/null | head -1)"
[ -n "$GPU" ] || GPU="$(lspci 2>/dev/null | grep -iE 'vga|3d' | sed 's/^[^:]*: //' | head -1) (no CUDA GPU: no local model inference or GPU upscaling here)"
ADDR="$(hostname -I 2>/dev/null | awk '{print $1}')"
DISK="$(df -h "$HOME" | awk 'NR==2{print $4 " free of " $2}')"
v() { command -v "$1" >/dev/null 2>&1 && "$1" --version 2>&1 | head -1 | cut -c1-60 || echo "not installed"; }
SERVICES="$(XDG_RUNTIME_DIR=/run/user/$(id -u) systemctl --user list-units --type=service --state=running --no-legend --plain 2>/dev/null \
  | awk '{print $1}' | grep -vE '^(hermes-gateway|dbus|at-spi|gpg-agent|pipewire|wireplumber|xdg-)' | sed 's/^/`/; s/$/`/' | paste -sd, - | sed 's/,/, /g')"
LISTEN="$(ss -ltnH 2>/dev/null | awk '{print $4}' | sed 's/.*://' | sort -un | awk -v lo="${API:-0}" '$1>=lo && $1<=lo+99' | paste -sd' ' -)"
FW="$(grep -oE 'LAN_SUBNETS="[^"]*"' /opt/hermes-template/host.conf 2>/dev/null | cut -d'"' -f2)"
if [ -n "$API" ]; then BLOCK="$((API+1))-$((API+99))"; FEEDBACK_PORT="$((API+99))"; else BLOCK="see registry"; FEEDBACK_PORT="?"; fi
mkdir -p "$(dirname "$OUT")"
cat > "$OUT" <<EOF
---
title: Host facts
type: system
status: active
owner: manager
updated: $(date +%F)
summary: "Where this project runs (OS, hardware, address, ports) and how its apps are served. Generated daily; don't edit."
tags: [system, host, generated]
---
# Host facts

_Generated by \`host-facts.sh\` on $(date '+%F %H:%M'). Read this before assuming an OS, a GPU, a path style or how to start something._

## The machine
- **OS:** $OS, $(uname -m), kernel $(uname -r). **Linux, not Windows:** forward-slash paths, case-sensitive file names, no \`.exe\`, \`.bat\` or Windows fonts. Code written on a Windows PC needs porting checks.
- **CPU:** $CPU. **RAM:** $RAM. **Disk:** $DISK.
- **GPU:** $GPU
- **Address on the LAN:** \`$ADDR\` (hostname \`$(hostname -s)\`). The owner reaches apps from their PC at \`http://$ADDR:<port>\`.

## Ports and how apps are served
- This project's block: **$BLOCK** (API server on ${API:-?}, localhost only). Bind apps to \`0.0.0.0\` on a port in the block; the firewall lets the LAN in (${FW:-the LAN subnets in host.conf}) and nothing else.
- \`$FEEDBACK_PORT\` is the owner's feedback inbox (the Mark overlay; see \`system/overview.md\`).
- **Serve an app as a systemd user service:** \`~/.config/systemd/user/<name>.service\` with \`Restart=always\`, \`WantedBy=default.target\`; \`systemctl --user daemon-reload && systemctl --user enable --now <name>\`; restart after a change. No sudo. Linger is on, so services start at boot without anyone logged in.
- **Running now:** ${SERVICES:-no app services yet}. **Listening in this block:** ${LISTEN:-none}.

## Tools on this host
- python3: $(v python3) · uv: $(v uv) · node: $(v node) · npm: $(v npm) · git: $(git --version 2>/dev/null | cut -c13-) · ffmpeg: $(ffmpeg -version 2>/dev/null | head -1 | cut -d' ' -f3)
- Use \`/usr/bin/python3\` for scripts that need PyYAML; Hermes' own python lacks it.
- A headless Chromium is available to the bots' browser tool (screenshots, vision); Node is here for front-end builds and \`npx\` tools.

## What isn't here
- No sudo for bots, no Docker, no display. Things that need the owner's PC (a GPU, a printer, Windows software) are done there, by the owner or a worker on the PC.
EOF
echo "host-facts: $OUT"
